@login = http://localhost:3000/user/login

@singup = http://localhost:3000/user/usersp

@getData = http://localhost:3000/user/getData

@addMateria = http://localhost:3000/user/addMateria

@cursar = http://localhost:3000/user/cursar

@getMateriaById = http://localhost:3000/user/getMateriaById/232323237


GET {{login}}
Content-Type: application/json

{
    "dni":"123456789",
    "password":"123"
}

###
POST {{singup}}
Content-Type: application/json

{
    "nombre": "Ivan",
    "dni":"123456789",
    "correo":"correof",
    "password": "123"


}

###
GET {{getData}}
mani: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkiLCJpYXQiOjE3MTkzMzU3MTcsImV4cCI6MTcyNTMzNTcxN30.zLByDYwVeQnuNYmpqL4xKphX-9rGg1CUCNNC6LKHMOE


###
POST {{addMateria}}
mani: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkiLCJpYXQiOjE3MTkzMzU3MTcsImV4cCI6MTcyNTMzNTcxN30.zLByDYwVeQnuNYmpqL4xKphX-9rGg1CUCNNC6LKHMOE
Content-Type: application/json

{
    "nombre": "Geografia"
}

###
POST {{cursar}}
mani: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkiLCJpYXQiOjE3MTkzMzU3MTcsImV4cCI6MTcyNTMzNTcxN30.zLByDYwVeQnuNYmpqL4xKphX-9rGg1CUCNNC6LKHMOE
Content-Type: application/json

{
  "dni": "123456789",
  "idMateria": 1
}

### Obtener materias cursadas por un alumno 
GET {{getMateriaById}}
mani: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkiLCJpYXQiOjE3MTkzMzU3MTcsImV4cCI6MTcyNTMzNTcxN30.zLByDYwVeQnuNYmpqL4xKphX-9rGg1CUCNNC6LKHMOE